export const BRAND_THEME_OPTIONS = [
  { value: "", title: "Default (global)" },
  { value: "beavercreek", title: "Beaver Creek" },
  { value: "breckenridge", title: "Breckenridge" },
  { value: "crestedbutte", title: "Crested Butte" },
  { value: "epicmountainrentals", title: "Epic Mountain Rentals" },
  { value: "epicpass", title: "Epic Pass" },
  { value: "epicpass2025", title: "Epic Pass 2025" },
  { value: "heavenly", title: "Heavenly" },
  { value: "hunter", title: "Hunter" },
  { value: "keystone", title: "Keystone" },
  { value: "kirkwood", title: "Kirkwood" },
  { value: "mountsunapee", title: "Mount Sunapee" },
  { value: "mtsnow", title: "Mt Snow" },
  { value: "myepicgear", title: "My Epic Gear" },
  { value: "northstar", title: "Northstar" },
  { value: "okemo", title: "Okemo" },
  { value: "parkcity", title: "Park City" },
  { value: "sevensprings", title: "Seven Springs" },
  { value: "snow", title: "Snow" },
  { value: "stevenspass", title: "Stevens Pass" },
  { value: "stowe", title: "Stowe" },
  { value: "vail", title: "Vail" },
  { value: "whistlerblackcomb", title: "Whistler Blackcomb" },
] as const;
