import type { Metadata, Viewport } from "next";
import { ContentstackLivePreview } from "@/components/ContentstackLivePreview";
import { env } from "process";
import { fontPrompt } from "@/lib/fonts";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#317EFB",
  initialScale: 1,
  minimumScale: 1,
  width: "device-width",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme={env.NEXT_PUBLIC_THEME}
      className={fontPrompt.variable}
    >
      <head>
        <link rel="stylesheet" href="/styles/main.bundle.css" />
        <link rel="stylesheet" href="/styles/content.bundle.css" />
        <link rel="stylesheet" href="/styles/header.bundle.css" />
        <link rel="stylesheet" href="/styles/hero.bundle.css" />
      </head>

      <body className="personality_canvas personality_canvas--off font-sans antialiased">
        {/* {env.NEXT_PUBLIC_CONTENTSTACK_PREVIEW === "true" ? (
          <div
            role="alert"
            className="sticky top-0 z-50 w-full border-b border-amber-500/50 bg-amber-500/95 px-4 py-2 text-center text-sm font-medium text-amber-950 shadow-sm backdrop-blur-sm"
          >
            You are viewing the <strong>preview site</strong>. Content may be
            unpublished or in draft.
          </div>
        ) : null} */}

        {/* <Suspense fallback={<Skeleton className="h-14 w-full" />}>
          <ResortHeader data={DUMMY_RESORT_HEADER_DATA} />
        </Suspense> */}

        <div
          id="body-content"
          className="main-container position-top sr-modal-hidden "
          role="main"
        >
          <div className="container-fluid">{children}</div>
        </div>

        <ContentstackLivePreview />
      </body>
    </html>
  );
}
